runtime: python310
entrypoint: gunicorn -b :$PORT app:app

runtime_config:
  project: mlj-backend

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65
